baseURL = "http://example.org/"
languageCode = "en-us"
title = "Simon's Blog"
theme = "cactus"
# googleAnalytics = "UA-123-45"

[params]
    description = "My learning journey"
    mainSection = "posts"
    colortheme = "white" # dark, light, white, or classic
    css = ["css/custom.css"]
    showAllPostsOnHomePage = false
    postsOnHomePage = 5
    rss = true

[[params.social]]
    name = "github"
    link = "https://github.com/simon-truong"

[[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/simontruong2/"

[[params.social]]
    name = "email"
    link = "simontruong2@gmail.com" # no need for "mailto:" at the start