baseURL = "https://simon-truong.github.io/"
languageCode = "en-au"
title = "Simon's Blog"
theme = "cactus"
copyright = "Simon Truong"
googleAnalytics = "G-KSE6GMXXEZ"

[params]
    description = "My learning journey"
    mainSection = "posts"
    colortheme = "white" # dark, light, white, or classic
    css = ["css/custom.css"]
    showAllPostsOnHomePage = false
    postsOnHomePage = 5
    rss = true
    dateFormat = "2 January, 2006"
    showReadTime = true

[[params.social]]
    name = "github"
    link = "https://github.com/simon-truong"

[[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/simontruong2/"

[[params.social]]
    name = "email"
    link = "simontruong2@gmail.com" # no need for "mailto:" at the start

[[params.social]]
    name = "rss"
    link = "/index.xml"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2